---
title: "Trelliscope example"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## Load packages
pacman::p_load(tidyverse, readr, stringr)
#devtools::install_github("hafen/trelliscopejs")
pacman::p_load(trelliscopejs)

## Import Data
Artists  <- read_csv("https://media.githubusercontent.com/media/MuseumofModernArt/collection/master/Artists.csv")
Artworks <- read_csv("https://media.githubusercontent.com/media/MuseumofModernArt/collection/master/Artworks.csv")


## Subset data
Artworks2 <- Artworks %>% 
  mutate(Nationality = str_replace_all(Nationality,"[()]",""),
         Gender = str_replace_all(Gender, "[()]",""),
            #URL =  str_sub(URL,8,-1)
         URL = as.character(URL)) %>% 
  select(Title, ThumbnailURL, URL, 
         Artist, Nationality, Gender,
         Medium, Classification, Department,
         Dimensions, `Height (cm)`, `Width (cm)`) %>% 
  filter(Medium == "Oil on canvas") %>% 
  mutate(panel = img_panel(ThumbnailURL),
         URL2 = ifelse(is.na(URL), "http://www.moma.org/collection/works", URL))

## Run Trelliscope 
Artworks2  %>% 
  trelliscope(name = "MOMA Collection",
              desc = "The Museum of Modern Art (MoMA) Collection",
              nrow = 3, ncol = 8,
              state = list(labels = c("Artist","Title","URL2")),
              path = "moma")

```